import { Component } from '@angular/core';
import { RandomItemSelectorComponent } from "../../shared/random-item-selector-component/random-item-selector-component";
import { DieRollerComponent } from '../../shared/die-roller-component/die-roller-component';
import { MultiRandomItemSelector } from "../../shared/multi-random-item-selector/multi-random-item-selector";

@Component({
  selector: 'app-home',
  imports: [RandomItemSelectorComponent, DieRollerComponent, MultiRandomItemSelector],
  templateUrl: './home.html',
  styleUrl: './home.css'
})
export class Home {
  shortDescriptionList: string[] = [
    'Ancient',
    'Broken',
    'Cunning',
    'Deadly',
    'Forgotten',
    'Hidden',
    'Hostile',
    'Lost',
    'Mysterious',
    'Powerful',
    'Sacred',
    'Secret',
    'Strange',
    'Suspicious',
    'Temporary',
    'Unstable',
    'Valuable',
    'Violent',
    'Weak',
    'Wounded'
  ];

  longDescriptionList: string[] = [
    'Abandoned',
    'Ancient',
    'Angry',
    'Ashen',
    'Awakened',
    'Balanced',
    'Beautiful',
    'Bitter',
    'Blessed',
    'Bloody',
    'Broken',
    'Burning',
    'Chaotic',
    'Clever',
    'Cold',
    'Corrupted',
    'Cracked',
    'Cursed',
    'Distant',
    'Divine',
    'Doomed',
    'Drifting',
    'Dying',
    'Empty',
    'Enchanted',
    'Endless',
    'Exiled',
    'Faded',
    'Faithful',
    'False',
    'Familiar',
    'Fearful',
    'Fierce',
    'Forgotten',
    'Fractured',
    'Fragile',
    'Frozen',
    'Gentle',
    'Glorious',
    'Greedy',
    'Grim',
    'Haunted',
    'Hidden',
    'Holy',
    'Hopeful',
    'Hostile',
    'Hungry',
    'Illusory',
    'Immortal',
    'Incomplete',
    'Invisible',
    'Joyful',
    'Lonesome',
    'Lost',
    'Loyal',
    'Mad',
    'Majestic',
    'Mysterious',
    'Muted',
    'Natural',
    'Noble',
    'Obscured',
    'Old',
    'Oppressive',
    'Painful',
    'Parasitic',
    'Patient',
    'Poisoned',
    'Powerful',
    'Primal',
    'Proud',
    'Quiet',
    'Radiant',
    'Reckless',
    'Reclusive',
    'Restless',
    'Sacred',
    'Savage',
    'Secret',
    'Shattered',
    'Shifting',
    'Silent',
    'Sinister',
    'Sleeping',
    'Smiling',
    'Solitary',
    'Strange',
    'Strong',
    'Stubborn',
    'Subtle',
    'Tainted',
    'Thirsty',
    'Timid',
    'Twisted',
    'Unbound',
    'Unseen',
    'Unstable',
    'Vengeful',
    'Wild',
    'Withered'
  ];

  
}
